
USE MASTER
GO

IF  NOT EXISTS (SELECT * FROM sys.databases WHERE name = N'FAF12_TRESNAL')
    BEGIN  CREATE DATABASE [FAF12_TRESNAL]
    END
GO

ALTER DATABASE [FAF12_TRESNAL]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE [FAF12_TRESNAL] SET MULTI_USER
GO
USE MASTER

  RESTORE DATABASE [FAF12_TRESNAL]
-- FROM  DISK = N'C:\BACKUP\Gasa.bak'
-- para restaurar en el servidor 15 de docker
  FROM  DISK = N'/var/opt/mssql/data/FAF12_TRESNAL_2022_11_27_234001_26779.bak'
  WITH REPLACE
GO

/***** EN CASO DE NO TENER ESPACIO EN DISCO****/
/*
USE MASTER
ALTER DATABASE [FAF12_NOMBRE_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [FAF12_NOMBRE_DB] FROM  DISK = N'D:\BACKUP\NOMBRE_BACKUP.bak' WITH  FILE = 1,  MOVE N'FAF_XRM12_Data' TO N'f:\DATA\FAF12_NOMBRE_DB.mdf',  MOVE N'FAF_XRM12_Log' TO N'e:\DATA\FAF12_NOMBRE_DB.ldf',  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [FAF12_NOMBRE_DB] SET MULTI_USER
*/


USE [FAF12_TRESNAL]

UPDATE FAFRol SET BandejaEntradaURL = null, CuentaPOP = null, PasswordCuentaPOP = null

TRUNCATE TABLE FAFAnalytics

TRUNCATE TABLE FAFContenidosRelacionados

TRUNCATE TABLE FAFContenidoCanal

TRUNCATE TABLE FAFContenidoValoracion

TRUNCATE TABLE FTLog

DELETE FROM FAFContenido

UPDATE BSPersona SET Email = 'desajavafinn@gmail.com'

UPDATE BSOrganizacion SET Email = 'desajavafinn@gmail.com'

UPDATE FAFUsuario SET Activo = 1, IntentosLogin = null, LockDate = null, Email = 'desajavafinn@gmail.com', Password = '', MailPassword = ''

UPDATE FAFConfig SET VALOR = '' WHERE ASPECTO IN (
  'FAF_CENTRAL_MAILBOX',
  'FAF_CENTRAL_MAILBOX_FROMNAME',
  'FAF_CENTRAL_MAILBOX_PASS',
  'FAF_CENTRAL_MAILBOX_USER',
  'FAF_INCOMING_MAIL_HOST',
  'FAF_INCOMING_MAIL_PORT',
  'FAF_INCOMING_MAIL_SSL',
  'FAF_INCOMING_MAIL_TYPE'
)

UPDATE FAFConfig SET Valor=0 WHERE ASPECTO IN (
  'FAF_PS_PWD_DIGIT',
  'FAF_PS_PWD_DURATION',
  'FAF_PS_PWD_LENGTH',
  'FAF_PS_PWD_LETTER',
  'FAF_PS_PWD_SPECIAL'
)

UPDATE FAFDiccionario SET OrigenDatos = ''

UPDATE FAFDiccionario SET DisponibleMobile = 0

DELETE FROM FTLOG WHERE JOB_ID IN (SELECT JOB_ID FROM FTJob WHERE JOB_NOMBRE LIKE '%mobile%')

DELETE FROM FTJobPersonaAlerta WHERE JOB_ID IN (SELECT JOB_ID FROM FTJob WHERE JOB_NOMBRE LIKE '%mobile%')

DELETE FROM FTJobStep WHERE JOB_ID IN (SELECT JOB_ID FROM FTJob WHERE JOB_NOMBRE LIKE '%mobile%')

DELETE FROM FTJob WHERE JOB_NOMBRE LIKE '%mobile%'

UPDATE TPCasoActividad SET Finalizada = 1, FechaFinAsignacion = getdate()
WHERE TransaccionID IN (SELECT TransaccionID FROM TPCaso WHERE BPMProcesoID IN (SELECT BPMProcesoID FROM TPBPMProceso WHERE Codigo LIKE 'sincro_mobile%'))
      AND finalizada = 0

UPDATE FTJob SET job_tieneschedule = 0

/* Este update se corre para que no redirija a go*/
UPDATE FAFCONFIG SET Valor = 'false' where Aspecto = 'MODOF4'
GO
